### ISSUE TITLE
Feature request: make annotation field read-only on new row

### ISSUE THREAD

**Issue by KatieMFritz** [marionnewlevant/craft-annotated_notes#3]
Currently, the annotation field is editable before you save the entry. If you put text in it and save, it gets wiped out later, but the twig code doesn't get rendered. 

I think the easiest solution (hopefully) would be to disable manual editing for that field in all cases.

**Comment by marionnewlevant** [comment]
I think that what happens is that if you leave the field blank when you first add the row, the annotation gets the twig code, but if you put a value there, it gets that value. And in neither case can you change the annotation once it is set.

Given how this field is a fairly thin layer over the Craft table field, this would require hijacking the new row javascript to  have it know to make the second column not be editable. I'd like to be able to do this, but it adds too much complexity (and technical debt I'd rather not have to deal with)

**Comment by KatieMFritz** [comment]
That's fair! Thanks for responding (and thanks again for the very useful plugin).
