### ISSUE TITLE
Question: how to get current author as a twig variable?

### ISSUE THREAD

**Issue by KatieMFritz** [marionnewlevant/craft-annotated_notes#4]
I'd love to automatically include the person who made the note in my twig annotation code, but I'm not sure how to do that. Has anyone already figured this out? 

I found [this answer for Craft 2](https://craftcms.stackexchange.com/questions/19809/get-the-author-of-current-entry-version), but I'm hoping there's an easier way in Craft 3.

**Comment by marionnewlevant** [comment]
Try `{{ currentUser.name }}`
